### PR TITLE
Jb conditions css

### PR DESCRIPTION
**Pull request by jbevis**
### What's this PR do?
I added an additional check in the filter logic so that all the trails data is rendered if none match the difficulty level search. Prior, this was resetting the store and removing all the results.

### Pre-Merge TODOs
Before: 
screen shot 2017-06-06 at 10 30 46 am

After: 
screen shot 2017-06-06 at 10 34 14 am

### Learning
No research just adding an id and updating css

### Where should the reviewer start?
index.css line 209

### Any background context you want to provide?
The image pulls in from the api very small, so was suggested to eval to increase size for visalbility

### What gif best describes this PR or how it makes you feel?
[This one](https://media.giphy.com/media/13FrpeVH09Zrb2/giphy.gif)

### CODE REVIEW

**Comment by letakeane** [comment]
I can see it so much BETTER now! No, but it's good. The UI is much clearer! It might be helpful to add a label? I'm presuming that there's also a linguistic difficulty in the info - maybe having the icon AND the text? "Medium difficulty" or something, to further clarify.

**Comment by JohnBinning** [comment]
I've always believed in your ability to adjust the size of an image, and I'm happy to report you to this date have never let me down in this regard.  Fantastic work Jack.

**Comment by jbevis** [comment]
Thanks Leta, I agree, this card component definitely got the least attention, which can be further styled up. The image is for trail conditions e.g. muddy, closed, clear, etc, so the 'minor issues' right below is actually the text accompanying the image. But I agree, that's not overtly clear in the UI right now.

**Comment by jbevis** [comment]
John, glad I didn't let you down buddy.

**Comment by jbevis** [comment]
@joshuajhun, @Tman22, @rrgayhart for your reviewing pleasure

**Pull request merged**
