### PR TITLE
Updated filter by difficulty logic to return all the trails if no tra…

### PR DESCRIPTION
**Pull request by jbevis**
…ils match difficulty level, was previously resetting store and wiping out search results

### CODE REVIEW

**Comment by jbevis** [comment]
### What's this PR do?
I added an additional check in the filter logic so that all the trails data is rendered if none match the difficulty level search. Prior, this was resetting the store and removing all the results.

### Pre-Merge TODOs
This may ultimately end up being refactored further, right now this is all talking to the redux store, but I may end up leveraging state via react without using redux on this portion of the app.

### Learning
Not a ton of extra learning, adding an extra conditional to check the result of the reduce, I tried using a ternary, but felt that it wasn't as readable.

### Where should the reviewer start?
CardGrid.js line line 14

### Any background context you want to provide?
Filter by difficulty function takes in a difficulty value from the drop down, sets state to that string, then I reduce over the trail results to filter out matching trails into a new object, this is then sent to the redux store, where it then is re rendered.

### What gif best describes this PR or how it makes you feel?
image

**Comment by hilvitzs** [comment]
The changes look great! I saw someone doing something similar but with ternaries. I thought it was pretty cool to see the different stuff you could do with that if you wanted to change it into that. Otherwise looks good! I think that should be a standing gif on 90% of pr's.

**Review by cjorda15 — COMMENTED** [review]
good logic/refactor on this!

**Comment by jbevis** [comment]
Thanks for the feedback guys.

@joshuajhun, @tman22, @rrgayhart for your reviewing pleasure

**Pull request merged**
