### PR TITLE
Jb welcome

### PR DESCRIPTION
**Pull request by jbevis**
### What's this PR do?
Very simple update to the app, I've added a separate component as a welcome screen, this is very basic right now, but will eventually hold links for different activities. Passing test file added as well.

### Pre-Merge TODOs
- [x] Screenshots Included
screen shot 2017-06-06 at 5 47 45 pm

 - [x] Tests Added
 - [ ] 2 PR reviews completed

### Learning
Simply breaking out jsx into a new component to be more manageable as the app scales

### Where should the reviewer start?
WelcomeCard.js

### Any background context you want to provide?
In lieu of a landing page, this component will ultimately welcome the user and provide options for different activities.

### What gif best describes this PR or how it makes you feel?
[this one](https://media.giphy.com/media/ASd0Ukj0y3qMM/giphy.gif)

### CODE REVIEW

**Comment by Adamj1232** [comment]
Yo bigDawg! Looks great, nice touch with the font. Very smooth design...maybe lighten the opacity on your copyright...maybenot
Good work!

**Review by DBULL7 — COMMENTED** [review]
Looks good sir!

**Comment by jbevis** [comment]
Thanks for the feedback guys, Adam, I agree that is popping a little too much.

@joshuajhun, @tman22, @rrgayhart for review.

**Comment by ghost** [comment]
This landing page looks good! The colors you chose for the text and button go well with the background image.

**Pull request merged**
